### PR TITLE
Adds RobôCIn brands and info

### PR DESCRIPTION
**Pull request by ersaraujo**
## 👀 Overview:

This PR adds RobôCIn brand information, as well as its usage rules.

## ⚠️ Notes:
- RoboCIn has two color versions for its logo, the rules of use for each of them are available in the [brand manual](https://drive.google.com/file/d/12KQhLZm7lmYWIkskkscVzr2hQm2L88uy/view?usp=sharing) and must be followed by the organization.
- the ```_white``` prefix was used to differentiate the two versions.

## ☎️ Other questions:
If you have any further questions about using the RobôCIn brand, contact us:
- robocin@cin.ufpe.br
- [robocinufpe](https://instagram.com/robocinufpe)

### CODE REVIEW

**Comment by ersaraujo** [comment]
@rafael-lang can you review?

**Comment by rafael-lang** [comment]
Please change the last line of the README file from:

`- [Brand Manual](https://drive.google.com/file/d/12KQhLZm7lmYWIkskkscVzr2hQm2L88uy/view?usp=sharing)`

to:

`- Guidelines: [RobôCIn Brand Manual](https://drive.google.com/file/d/12KQhLZm7lmYWIkskkscVzr2hQm2L88uy)`

**Comment by ersaraujo** [comment]
@rafael-lang the requested changes have been made.

**Review by rafael-lang — APPROVED** [review]
Everything ok

**Pull request merged**
